
export const TAX_BANDS = [
  { limit: 800000, rate: 0.00, label: 'First 800k' },
  { limit: 2200000, rate: 0.15, label: 'Next 2.2m' },
  { limit: 9000000, rate: 0.18, label: 'Next 9m' },
  { limit: 13000000, rate: 0.21, label: 'Next 13m' },
  { limit: 25000000, rate: 0.23, label: 'Next 25m' },
  { limit: Infinity, rate: 0.25, label: 'Above 50m' },
];

export const VAT_RATE = 0.075;
export const FOSSIL_FUEL_SURCHARGE_RATE = 0.05;
export const DIGITAL_ASSET_CGT_RATE = 0.10;

export const EXCHANGE_RATES = {
  NGN: 1,
  USD: 1550,
  GBP: 1980,
  EUR: 1680
};

export const INDUSTRY_CATEGORIES = [
  'Professional Services',
  'Retail & Trade',
  'Technology & Fintech',
  'Digital Assets Trading',
  'Agriculture & Plantation',
  'Manufacturing (Priority)',
  'Mining Operations',
  'Petroleum (Upstream)',
  'Education & Healthcare'
];

export const FAQ_DATA = [
  {
    question: "Who is exempt from Income Tax in 2025?",
    answer: "Individuals earning the National Minimum Wage or less are exempt from PIT (Section 58). Small companies with turnover below N50m are also exempt from CIT (Section 56).",
    example: "If you are a cleaner earning N70,000 monthly (N840,000 yearly), your first N800,000 is tax-free, and your remaining N40,000 falls under the lowest bracket, but typically minimum wage earners pay zero tax."
  },
  {
    question: "What is the tax rate for Digital Assets (Crypto)?",
    answer: "Under Section 4 of the 2025 Act, gains from the disposal of digital assets (including cryptocurrencies and NFTs) are subject to a 10% Capital Gains Tax (CGT).",
    example: "If you bought 1 ETH for N3,000,000 and sold it for N4,500,000, your gain is N1,500,000. You owe 10% of that gain, which is N150,000 in CGT."
  },
  {
    question: "What items are zero-rated for VAT (0%)?",
    answer: "Section 187 lists: Basic food items, educational books, locally produced agricultural chemicals, veterinary medicine, and electricity generated by GENCOs for the grid.",
    example: "When you buy a locally published textbook for N5,000, the VAT added is N0. If you buy a luxury imported watch, 7.5% VAT is added."
  },
  {
    question: "How does the 'Small Company' CIT exemption work?",
    answer: "Companies with a gross turnover of N50 million or less are classified as Small Companies. They are subject to 0% Companies Income Tax (CIT), provided they file their returns on time (Section 56).",
    example: "A bakery with N35 million annual sales pays 0% CIT. A large supermarket with N120 million sales pays the standard 30% CIT on profits."
  },
  {
    question: "Is remote work for foreign companies taxable in Nigeria?",
    answer: "Yes. If you are a resident of Nigeria (living here for more than 183 days), you are taxed on your global income, regardless of where the employer is located (Section 10).",
    example: "A software developer in Enugu working for a US company and earning $2,000/month must convert that to Naira and include it in their PIT self-assessment."
  },
  {
    question: "What is the Electronic Transfer Levy (ETL)?",
    answer: "A flat N50 levy is charged on electronic transfers of N10,000 and above between accounts in different banks (Section 89).",
    example: "If you transfer N15,000 from your Kuda account to a friend's GTBank account, N50 is deducted. A N5,000 transfer attracts no ETL."
  },
  {
    question: "Are medical services VAT-exempt?",
    answer: "Yes, medical and pharmaceutical products and services are generally exempt from VAT to ensure healthcare remains affordable (Section 188).",
    example: "A bill for a N50,000 surgery at a private hospital should not have an additional 7.5% VAT added to the final amount."
  },
  {
    question: "Does the 2025 Act affect Rent Stamp Duty?",
    answer: "Yes, Section 104 mandates that all corporate lease agreements exceeding N100,000 per annum must be stamped. The rate is 0.75% of the total rent.",
    example: "For a shop lease of N1,000,000 per year, the stamp duty is N7,500. This is usually paid by the tenant to make the agreement legally binding."
  },
  {
    question: "What is the Fossil Fuel Surcharge (FFS)?",
    answer: "Under Section 159, a 5% surcharge is levied on the importation or local production of fossil fuels, excluding CNG and LPG used for domestic purposes.",
    example: "A company importing N10,000,000 worth of industrial diesel will pay an additional N500,000 as a fossil fuel surcharge."
  }
];
